### ISSUE TITLE
.ico support

### ISSUE THREAD

**Issue by shanebo** [lukeed/mrmime#3]
It'd be great if `.ico` was support out of the box. Thankfully you expose the `mimes` table, but it'd be great for this common extension to be natively mapped to the `image/x-icon` content type. Thanks for considering and for this great package!

**Comment by lukeed** [comment]
Hey, thanks!

All experimental types (x-*) and vendor-specific types are ignored. Making exceptions here and there is a slippery slope and the dividing line becomes less clear.

You can add this in to your own dictionary by directly assigning it. There's an example in the readme and throughout the tests.

Sorry but please do use the assignment approach! That was an intentional part of the pkg design.
