### ISSUE TITLE
application/javascript is deprecated

### ISSUE THREAD

**Issue by JoakimCh** [lukeed/mrmime#8]
> Per the [IANA Media Types registry](https://www.iana.org/assignments/media-types/media-types.xhtml#text), [RFC 9239](https://www.rfc-editor.org/rfc/rfc9239.html), and the [HTML specification](https://html.spec.whatwg.org/multipage/scripting.html#scriptingLanguages:text/javascript), JavaScript content should always be served using the MIME type text/javascript. No other MIME types are considered valid for JavaScript, and using any MIME type other than text/javascript may result in scripts that do not load or run.

Source: [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types#textjavascript)

What else does it use that is deprecated? I didn't check.

**Comment by broofa** [comment]
[Hey @lukeed , 'just stumbled across your project.  It's always nice to see other folks working in the MIME space.]

I ran into this same issue with `mime`.  The problem is that `mime-db` doesn't currently include `extensions` for the `text/javascript` type.  Or, rather, [it does](https://github.com/jshttp/mime-db/blob/master/db.json#L8035-L8040) but that change hasn't been published yet.   (Change was in May 2022, last release of `mime-db` was Feb 2022).

Maybe file an issue with the `mime-db` project to see if they'll push a new release for you.

FWIW, this issue prompted me to remove `mime-db` from the `package.json#dependencies` and, instead, have the [build script pull directly](https://github.com/broofa/mime/blob/main/scripts/build.ts#L10-L11) from the `mime-db` source on GH.

On a related note, you may want to take a look at my [mime-score](https://github.com/broofa/mime-score) module.  It contains the logic 'mime' uses to select which mime-type an extension should map to when when there are extension conflicts.  I've got [a PR to switch](https://github.com/jshttp/mime-types/pull/42) `mime-types` use this logic as well... if/when I find time to work on it.

**Comment by benmccann** [comment]
Yeah, `mime-db` looks correct:

https://github.com/jshttp/mime-db/blob/a76e5a824c228e2e58363c9404e42a54ee1d142f/src/iana-types.json#L9942

I think we probably just need a new release of `mrmime`?

**Comment by benmccann** [comment]
thank you Luke!
